BasketballTickets/Models/League.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketballTickets.Models
{
    public class League
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LogoPath { get; set; }

        public ICollection<Team> Team { get; set; }
    }
}

BasketballTickets/Controllers/LeaguesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BasketballTickets.Data;
using BasketballTickets.Models;
using Microsoft.AspNetCore.Authorization;
using FileUploadControl;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace BasketballTickets.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LeaguesController : BaseController
    {
        private readonly IUploadableFile _upload;
        private readonly String logoFolder;

        public LeaguesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IUploadableFile upload) : base(context, userManager)
        {
            _upload = upload;
            logoFolder = "leagues";
        }

        // GET: Leagues
        public async Task<IActionResult> Index()
        {
            return View(await _context.Leagues.ToListAsync());
        }

        // GET: Leagues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var league = await _context.Leagues
                .FirstOrDefaultAsync(m => m.Id == id);
            if (league == null)
            {
                return NotFound();
            }

            return View(league);
        }

        // GET: Leagues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Leagues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,LogoPath")] League league, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                league.LogoPath = "~/uploads/" + logoFolder + "/" + file.FileName.Trim();
                _upload.UploadFile(file, logoFolder);
                _context.Add(league);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(league);
        }

        // GET: Leagues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var league = await _context.Leagues.FindAsync(id);
            if (league == null)
            {
                return NotFound();
            }
            return View(league);
        }

        // POST: Leagues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,LogoPath")] League league, IFormFile file)
        {
            if (id != league.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        league.LogoPath = "~/uploads/" + logoFolder + "/" + file.FileName.Trim();
                        _upload.UploadFile(file, logoFolder);
                    } else
                    {
                        league.LogoPath = _context.Leagues.AsNoTracking().Where(l => l.Id == league.Id).First().LogoPath;
                    }

                    _context.Update(league);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeagueExists(league.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(league);
        }

        // GET: Leagues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var league = await _context.Leagues
                .FirstOrDefaultAsync(m => m.Id == id);
            if (league == null)
            {
                return NotFound();
            }

            return View(league);
        }

        // POST: Leagues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var league = await _context.Leagues.FindAsync(id);
            _context.Leagues.Remove(league);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeagueExists(int id)
        {
            return _context.Leagues.Any(e => e.Id == id);
        }
    }
}

BasketballTickets/Views/Leagues/Create.cshtml
@model BasketballTickets.Models.League

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>League</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data" asp-controller="Leagues">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LogoPath" class="control-label"></label>
                <input type="file" name="file" asp-for="LogoPath" class="form-control" />
                <span asp-validation-for="LogoPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="glyphicon glyphicon-ok"></i> Create
                </button>
            </div>
        </form>
    </div>
</div>

<div class="align-right">
    <button class="btn btn-primary">
        <a asp-action="Index"><span class="glyphicon glyphicon-share-alt"></span> Back to List</a>
    </button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BasketballTickets/Views/Leagues/Delete.cshtml
@model BasketballTickets.Models.League

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LogoPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LogoPath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-primary">
            <i class="glyphicon glyphicon-trash"></i> Delete
        </button>
        <div class="align-right">
            <button class="btn btn-primary">
                <a asp-action="Index"><span class="glyphicon glyphicon-share-alt"></span> Back to List</a>
            </button>
        </div>
    </form>
</div>

BasketballTickets/Views/Leagues/Details.cshtml
@model BasketballTickets.Models.League

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LogoPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LogoPath)
        </dd>
    </dl>
</div>
<div>
    <button class="btn btn-primary">
        <a asp-action="Edit" asp-route-id="@Model.Id"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
    </button>
    <div class="align-right">
        <button class="btn btn-primary">
            <a asp-action="Index"><span class="glyphicon glyphicon-share-alt"></span> Back to List</a>
        </button>
    </div>
</div>

BasketballTickets/Views/Leagues/Edit.cshtml
@model BasketballTickets.Models.League

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>League</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data" asp-controller="Leagues">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LogoPath" class="control-label"></label>
                <input type="file" name="file" asp-for="LogoPath" class="form-control" />
                <span asp-validation-for="LogoPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="glyphicon glyphicon-ok"></i> Save
                </button>
            </div>
        </form>
    </div>
</div>

<div class="align-right">
    <button class="btn btn-primary">
        <a asp-action="Index"><span class="glyphicon glyphicon-share-alt"></span> Back to List</a>
    </button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BasketballTickets/Views/Leagues/Index.cshtml
@model IEnumerable<BasketballTickets.Models.League>

@{
    ViewData["Title"] = "Leagues";
}

<h2 class="center center-bold">@ViewData["Title"]</h2>

<p>
    <button class="btn btn-primary">
        <a asp-action="Create"><span class="glyphicon glyphicon-plus-sign"></span> Create New </a>
    </button>
</p>
<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="colored-border" onclick="location.href = '@(Url.Action("Details", "Leagues", new { id = item.Id }))'">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <img src="@item.LogoPath" height="40" width="20" asp-append-version="true" />
                </td>
                <td>
                    <div class="btn-group btn-group-toggle">
                        <label class="btn btn-primary">
                            <a asp-action="Edit" asp-route-id="@item.Id"><span class="glyphicon glyphicon-cog"></span> Edit</a>
                        </label>
                        <label class="btn btn-primary">
                            <a asp-action="Delete" asp-route-id="@item.Id"><span class="glyphicon glyphicon-trash"></span> Delete</a>
                        </label>
                    </div>
                </td>
            </tr>
            }
        </tbody>
</table>