BasketballTickets/Controllers/ArenasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BasketballTickets.Data;
using BasketballTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BasketballTickets.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ArenasController : BaseController
    {
        public ArenasController(ApplicationDbContext context, UserManager<ApplicationUser> userManager) : base(context, userManager)
        {
        }

        // GET: Arenas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Arenas.ToListAsync());
        }

        // GET: Arenas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arena = await _context.Arenas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (arena == null)
            {
                return NotFound();
            }

            return View(arena);
        }

        // GET: Arenas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Arenas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Capacity")] Arena arena)
        {
            if (ModelState.IsValid)
            {
                _context.Add(arena);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(arena);
        }

        // GET: Arenas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arena = await _context.Arenas.FindAsync(id);
            if (arena == null)
            {
                return NotFound();
            }
            return View(arena);
        }

        // POST: Arenas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Capacity")] Arena arena)
        {
            if (id != arena.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(arena);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArenaExists(arena.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(arena);
        }

        // GET: Arenas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arena = await _context.Arenas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (arena == null)
            {
                return NotFound();
            }

            return View(arena);
        }

        // POST: Arenas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var arena = await _context.Arenas.FindAsync(id);
            _context.Arenas.Remove(arena);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArenaExists(int id)
        {
            return _context.Arenas.Any(e => e.Id == id);
        }
    }
}

BasketballTickets/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BasketballTickets.Data;
using BasketballTickets.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace BasketballTickets.Controllers
{
    [Authorize]
    public class OrdersController : BaseController
    {
        public OrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager) : base(context, userManager)
        {
        }

        // GET: Orders
        public async Task<IActionResult> Index(bool showSuccessMsg)
        {
            if (showSuccessMsg != null)
            {
                ViewData["ShowSuccessMsg"] = showSuccessMsg;
            }

            var orders = _context.Orders.Include(o => o.User);

            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (!await _userManager.IsInRoleAsync(user, "Admin"))
            {
                orders.Where(o => o.UserId == user.Id);
            }

            return View(await orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName")] Order order)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                var userCartTickets = user.ShoppingCart.Tickets;
                order.User = user;
                order.Cost = userCartTickets.Sum(t => t.Price);
                order.Date = DateTime.Now;

                foreach (Ticket ticket in userCartTickets)
                {
                    ticket.Order = order;
                }
                user.ShoppingCart.Tickets.Clear();

                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { showSuccessMsg = true });
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return RedirectToAction("Index");
        }

        // GET: Orders/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Date,Cost,UserId")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

BasketballTickets/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BasketballTickets.Data;
using BasketballTickets.Models;
using Microsoft.AspNetCore.Authorization;
using FileUploadControl;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace BasketballTickets.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TeamsController : BaseController 
    {
        private readonly IUploadableFile _upload;
        private readonly String teamsFolder;

        public TeamsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IUploadableFile upload) : base(context, userManager)
        {
            _upload = upload;
            teamsFolder = "teams";
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Teams.Include(t => t.Arena).Include(t => t.League);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .Include(t => t.Arena)
                .Include(t => t.League)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            ViewData["ArenaId"] = new SelectList(_context.Arenas, "Id", "Name");
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "Name");
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,City,LogoPath,ArenaId,LeagueId")] Team team, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                team.LogoPath = "~/uploads/" + teamsFolder + "/" + file.FileName.Trim();
                _upload.UploadFile(file, teamsFolder);
                _context.Add(team);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArenaId"] = new SelectList(_context.Arenas, "Id", "Name", team.ArenaId);
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "Name", team.LeagueId);
            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            ViewData["ArenaId"] = new SelectList(_context.Arenas, "Id", "Name", team.ArenaId);
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "Name", team.LeagueId);
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,City,LogoPath,ArenaId,LeagueId")] Team team, IFormFile file)
        {
            if (id != team.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        team.LogoPath = "~/uploads/" + teamsFolder + "/" + file.FileName.Trim();
                        _upload.UploadFile(file, teamsFolder);
                    } else
                    {
                        team.LogoPath = _context.Teams.AsNoTracking().Where(t => t.Id == team.Id).First().LogoPath;
                    }
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArenaId"] = new SelectList(_context.Arenas, "Id", "Name", team.ArenaId);
            ViewData["LeagueId"] = new SelectList(_context.Leagues, "Id", "Name", team.LeagueId);
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .Include(t => t.Arena)
                .Include(t => t.League)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.FindAsync(id);
            _context.Teams.Remove(team);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.Id == id);
        }
    }
}

BasketballTickets/Views/Shared/_AdminPartial.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
    <button class="btn btn-secondary dropdown-toggle dropdown admin-dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            Admin <span class="glyphicon glyphicon-cog"></span>
        </a>

        <ul class="dropdown-menu">
            <li>
                <a asp-controller="Leagues" asp-action="Index" class="dropdown-item">Leagues</a>
                <a asp-controller="GameTypes" asp-action="Index" class="dropdown-item">Game Types</a>
                <a asp-controller="Arenas" asp-action="Index" class="dropdown-item">Arenas</a>
                <a asp-controller="Teams" asp-action="Index" class="dropdown-item">Teams</a>
                <a asp-controller="Games" asp-action="Index" class="dropdown-item">Games</a>
                <a asp-controller="Tickets" asp-action="Index" class="dropdown-item">Tickets</a>
                <a asp-controller="HighlightGames" asp-action="Index" class="dropdown-item">Highlight Games</a>
            </li>

            <li class="divider"></li>
            <li class="nav-header">
                <a asp-controller="Admin" asp-action="Reset" class="dropdown-item">Reset Store</a>
            </li>
        </ul>
    </button>
}

BasketballTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BasketballTickets</title>

    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" >
                <partial name="_AdminPartial" />
                <ul class="nav navbar-nav league-content">
                    @if (TempData["showLeagues"] != null)
                    {
                        foreach (var league in (List<League>)ViewData["Leagues"])
                        {
                            <li><a asp-area="" asp-controller="Home" asp-action="Index" asp-route-leagueId="@league.Id"><img src="@league.LogoPath" height="40" width="20" asp-append-version="true"/></a></li>
                        }
                    }
                </ul>
                <partial name="_LoginPartial" />
                <partial name="_ShoppingCartPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <br /><br />

    <div class="container body-content">
        @RenderBody()

        <br />
        <hr />
        <footer>
            <p>&copy; 2019 - BasketballTickets</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

BasketballTickets/Views/Shared/_ShoppingCartPartial.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{ 
    ICollection<Ticket> shoppingCart = (ICollection<Ticket>)ViewData["ShoppingCart"];
    shoppingCart = shoppingCart != null ? shoppingCart : new List<Ticket>();
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="navbar-right" style="margin-right: 4em;">
        <button class="btn dropdown-toggle dropdown admin-dropdown shopping-cart-btn">
            <a data-toggle="dropdown" class="dropdown-toggle">
                <i class="glyphicon glyphicon-shopping-cart shopping-cart"></i>
                @if (ViewData["CartQuantity"] != null && (int)ViewData["CartQuantity"] > 0)
                {
                    <sub id="cartQuantity" class="circle cart-notification">@ViewData["CartQuantity"]</sub>
                }
            </a>
            <ul class="dropdown-menu">
                <li id="navbar-tickets">
                    @foreach (Ticket ticket in shoppingCart)
                    {
                        <div id="nav-ticket-@ticket.Id" class="row shopping-cart-row">
                            <a asp-controller="Tickets" asp-action="Book" asp-route-gameId="@ticket.GameId" class="dropdown-item">
                                    <img src="@ticket.Game.HomeTeam.LogoPath" width="20px" height="16px" asp-append-version="true">
                                    <text>&nbsp;vs&nbsp;</text>
                                    <img src="@ticket.Game.AwayTeam.LogoPath" width="20px" height="16px" asp-append-version="true">
                                    <text>&nbsp;@BasketballTickets.Services.DateService.GetDayOfMonth(ticket.Game.Date)&nbsp;</text>
                                    <text>&nbsp;(Seat #@ticket.SeatNo)&nbsp;</text>
                                    <text>&nbsp;$@ticket.Price&nbsp;</text>
                                    <a onclick="removeFromCartRequest({ id: @ticket.Id, price: @ticket.Price })" class="btn btn-danger btn-xs"><i class="glyphicon glyphicon-remove"></i></a>
                            </a>
                        </div>
                    }
                </li>

                <li class="divider"></li>
                <text class="pull-right pad-right"><b>Total: $<text id="cartTotalPrice">@ViewData["TotalCartPrice"]</text></b></text>                    
                <br />
                <br />
                <li class="nav-header">
                    <div class="row">
                        <div class="col-md-offset-1 col-md-4">
                            <a  asp-controller="Orders" asp-action="Index" class="btn btn-primary">Orders <i class="glyphicon glyphicon-bookmark"></i></a>
                        </div>
                        <div class="col-md-offset-1 col-md-4">
                            <a asp-controller="Orders" asp-action="Create" class="btn btn-success dropdown-item"><b>Check out</b> <i class="glyphicon glyphicon-ok-sign"></i></a>
                        </div>
                    </div>
                </li>
            </ul>
        </button>
    </div>
}