BasketballTickets/Controllers/GameTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BasketballTickets.Data;
using BasketballTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BasketballTickets.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GameTypesController : BaseController
    {
        public GameTypesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager) : base(context, userManager)
        {
        }

        // GET: GameTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.GameTypes.ToListAsync());
        }

        // GET: GameTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameType = await _context.GameTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gameType == null)
            {
                return NotFound();
            }

            return View(gameType);
        }

        // GET: GameTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GameTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Order")] GameType gameType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gameType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gameType);
        }

        // GET: GameTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameType = await _context.GameTypes.FindAsync(id);
            if (gameType == null)
            {
                return NotFound();
            }
            return View(gameType);
        }

        // POST: GameTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Order")] GameType gameType)
        {
            if (id != gameType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gameType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameTypeExists(gameType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gameType);
        }

        // GET: GameTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gameType = await _context.GameTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gameType == null)
            {
                return NotFound();
            }

            return View(gameType);
        }

        // POST: GameTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gameType = await _context.GameTypes.FindAsync(id);
            _context.GameTypes.Remove(gameType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameTypeExists(int id)
        {
            return _context.GameTypes.Any(e => e.Id == id);
        }
    }
}

BasketballTickets/Views/GameTypes/Create.cshtml
@model BasketballTickets.Models.GameType

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>GameType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Order" class="control-label"></label>
                <input asp-for="Order" class="form-control" />
                <span asp-validation-for="Order" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="glyphicon glyphicon-ok"></i> Create
                </button>
            </div>
        </form>
    </div>
</div>

<div class="align-right">
    <button class="btn btn-primary">
        <a asp-action="Index"><span class="glyphicon glyphicon-share-alt"></span> Back to List</a>
    </button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BasketballTickets/Views/GameTypes/Delete.cshtml
@model BasketballTickets.Models.GameType

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GameType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-primary">
            <i class="glyphicon glyphicon-trash"></i> Delete
        </button>
        <div class="align-right">
            <button class="btn btn-primary">
                <a asp-action="Index"><span class="glyphicon glyphicon-share-alt"></span> Back to List</a>
            </button>
        </div>
    </form>
</div>

BasketballTickets/Views/GameTypes/Details.cshtml
@model BasketballTickets.Models.GameType

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>GameType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Order)
        </dd>
    </dl>
</div>
<div>
    <button class="btn btn-primary">
        <a asp-action="Edit" asp-route-id="@Model.Id"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
    </button>
    <div class="align-right">
        <button class="btn btn-primary">
            <a asp-action="Index"><span class="glyphicon glyphicon-share-alt"></span> Back to List</a>
        </button>
    </div>
</div>

BasketballTickets/Views/GameTypes/Edit.cshtml
@model BasketballTickets.Models.GameType

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>GameType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Order" class="control-label"></label>
                <input asp-for="Order" class="form-control" />
                <span asp-validation-for="Order" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    <i class="glyphicon glyphicon-ok"></i> Save
                </button>
            </div>
        </form>
    </div>
</div>

<div class="align-right">
    <button class="btn btn-primary">
        <a asp-action="Index"><span class="glyphicon glyphicon-share-alt"></span> Back to List</a>
    </button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BasketballTickets/Views/GameTypes/Index.cshtml
@model IEnumerable<BasketballTickets.Models.GameType>

@{
    ViewData["Title"] = "Game Types";
}

<h2 class="center center-bold">@ViewData["Title"]</h2>

<p>
    <button class="btn btn-primary">
        <a asp-action="Create"><span class="glyphicon glyphicon-plus-sign"></span> Create New </a>
    </button>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="colored-border" onclick="location.href = '@(Url.Action("Details", "GameTypes", new { id = item.Id }))'">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order)
                </td>
                <td>
                    <div class="btn-group btn-group-toggle">
                        <label class="btn btn-primary">
                            <a asp-action="Edit" asp-route-id="@item.Id"><span class="glyphicon glyphicon-cog"></span> Edit</a>
                        </label>
                        <label class="btn btn-primary">
                            <a asp-action="Delete" asp-route-id="@item.Id"><span class="glyphicon glyphicon-trash"></span> Delete</a>
                        </label>
                    </div>
                </td>
            </tr>
            }
        </tbody>
</table>