BasketballTickets/Models/HighlightGame.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BasketballTickets.Models
{
    public class HighlightGame
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public bool IsBanner { get; set; }

        public int GameId { get; set; }
        public Game Game { get; set; }
    }
}

BasketballTickets/Controllers/HighlightGamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BasketballTickets.Data;
using BasketballTickets.Models;
using Microsoft.AspNetCore.Identity;
using FileUploadControl;
using Microsoft.AspNetCore.Http;

namespace BasketballTickets.Controllers
{
    public class HighlightGamesController : BaseController
    {
        private readonly IUploadableFile _upload;
        private readonly String imageFolder;

        public HighlightGamesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IUploadableFile upload) : base(context, userManager)
        {
            _upload = upload;
            imageFolder = "highlights";
        }

        // GET: HighlightGames
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.HighlightGames.Include(h => h.Game);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: HighlightGames/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var highlightGame = await _context.HighlightGames
                .Include(h => h.Game)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (highlightGame == null)
            {
                return NotFound();
            }

            return View(highlightGame);
        }

        // GET: HighlightGames/Create
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "Id");
            return View();
        }

        // POST: HighlightGames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ImagePath,IsBanner,GameId")] HighlightGame highlightGame, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                highlightGame.ImagePath = "~/uploads/" + imageFolder + "/" + file.FileName.Trim();
                _upload.UploadFile(file, imageFolder);
                _context.Add(highlightGame);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "Id", highlightGame.GameId);
            return View(highlightGame);
        }

        // GET: HighlightGames/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var highlightGame = await _context.HighlightGames.FindAsync(id);
            if (highlightGame == null)
            {
                return NotFound();
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "Id", highlightGame.GameId);
            return View(highlightGame);
        }

        // POST: HighlightGames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ImagePath,IsBanner,GameId")] HighlightGame highlightGame, IFormFile file)
        {
            if (id != highlightGame.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        highlightGame.ImagePath = "~/uploads/" + imageFolder + "/" + file.FileName.Trim();
                        _upload.UploadFile(file, imageFolder);
                    }
                    else
                    {
                        highlightGame.ImagePath = _context.Leagues.AsNoTracking().Where(l => l.Id == highlightGame.Id).First().LogoPath;
                    }

                    _context.Update(highlightGame);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HighlightGameExists(highlightGame.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "Id", highlightGame.GameId);
            return View(highlightGame);
        }

        // GET: HighlightGames/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var highlightGame = await _context.HighlightGames
                .Include(h => h.Game)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (highlightGame == null)
            {
                return NotFound();
            }

            return View(highlightGame);
        }

        // POST: HighlightGames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var highlightGame = await _context.HighlightGames.FindAsync(id);
            _context.HighlightGames.Remove(highlightGame);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HighlightGameExists(int id)
        {
            return _context.HighlightGames.Any(e => e.Id == id);
        }
    }
}

BasketballTickets/Views/HighlightGames/Create.cshtml
@model BasketballTickets.Models.HighlightGame

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>HighlightGame</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data" asp-controller="HighlightGames">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input type="file" name="file" asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsBanner" /> @Html.DisplayNameFor(model => model.IsBanner)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="GameId" class="control-label"></label>
                <select asp-for="GameId" class="form-control" asp-items="ViewBag.GameId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BasketballTickets/Views/HighlightGames/Delete.cshtml
@model BasketballTickets.Models.HighlightGame

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HighlightGame</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsBanner)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsBanner)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Game.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BasketballTickets/Views/HighlightGames/Details.cshtml
@model BasketballTickets.Models.HighlightGame

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>HighlightGame</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsBanner)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsBanner)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Game)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Game.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BasketballTickets/Views/HighlightGames/Edit.cshtml
@model BasketballTickets.Models.HighlightGame

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>HighlightGame</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data" asp-controller="HighlightGames">>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input type="file" name="file" asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsBanner" /> @Html.DisplayNameFor(model => model.IsBanner)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="GameId" class="control-label"></label>
                <select asp-for="GameId" class="form-control" asp-items="ViewBag.GameId"></select>
                <span asp-validation-for="GameId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BasketballTickets/Views/HighlightGames/Index.cshtml
@model IEnumerable<BasketballTickets.Models.HighlightGame>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsBanner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Game)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsBanner)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Game.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>